apiVersion: apps/v1
kind: Deployment
metadata:
  name: excuse-deployment
  labels:
    app: excuse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: excuse
  template:
    metadata:
      labels: 
        app: excuse
    spec:
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 0
        fsGroup: 2000
      containers:
      - name: excuse
        image: gcr.io/paloaltonetworks/gunjan5/excuse:v2.1
        securityContext:
          privileged: true
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
              - CAP_SYS_ADMIN
        ports:
        - containerPort: 8080