apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodmorning-deployment
  labels:
    app: goodmorning
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goodmorning
  template:
    metadata:
      labels: 
        app: goodmorning
    spec:
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 0
        fsGroup: 2000 
      containers:
      - name: goodmorning
        image: gunjan5/goodmorning:v1.0 
        securityContext:
          privileged: true
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
              - CAP_SYS_ADMIN
        ports:
        - containerPort: 8080